# PBS configuration

# If submitting to a different project to your default, uncomment line below
# and change project code as appropriate; also set shortpath below
# project: v45

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

scheduler: slurm
queue: boost_usr_prod
walltime: 00:30:00
jobname: 1deg_jra55_ryf
project: ICT24_MHPC
jobname: access_om2_ryf
ncpus: 256
nnodes: 8
npernode: 32
#mem: 1000GB

# Model configuration
name: common
model: access-om2
input: /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2
submodels:
    - name: atmosphere
      model: yatm
      exe: /leonardo/home/userexternal/ntilinin/access-om2/bin/yatm_7ce7920.exe
      input:
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30
            - /leonardo/home/userexternal/ntilinin/make_ryf
      scheduler: slurm
      project: ICT24_MHPC
      walltime: 00:30:00
      queue: boost_usr_prod
      ncpus: 1
#      nnodes: 1
#      npernode: 32


    - name: ocean
      model: mom
      exe: /leonardo/home/userexternal/ntilinin/access-om2/bin/fms_ACCESS-OM_1883a84_libaccessom2_7ce7920.x
      input: 
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/chlorophyll/global.1deg/2020.05.30
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/initial_conditions/global.1deg/2020.10.22
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/surface_salt_restoring/global.1deg/2020.05.30
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/bathymetry/global.1deg/2020.10.22
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/vertical/global.1deg/2020.10.22
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/processor_masks/global.1deg/216.16x15/2020.05.30
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/tides/global.1deg/2020.05.30
      scheduler: slurm
      project: ICT24_MHPC
      walltime: 00:30:00
      queue: boost_usr_prod
      ncpus: 216
 #     nnodes: 8
 #     npernode: 32

    - name: ice
      model: cice5
      exe: /leonardo/home/userexternal/ntilinin/access-om2/bin/cice_auscom_360x300_24p_f39c802_libaccessom2_7ce7920.exe
      input: 
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/grids/global.1deg/2020.05.30
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/grids/global.1deg/2020.10.22
      scheduler: slurm
      project: ICT24_MHPC
      queue: boost_usr_prod
      walltime: 00:30:00
      ncpus: 24
#      nnodes: 8
#      npernode: 32

# Collation
collate:
  restart: true
  walltime: 00:30:00
  mem: 30GB
  scheduler: slurm
  project: ICT24_MHPC
  queue: boost_usr_prod
  ncpus: 4
#  nnodes: 8
#  npernode: 32
  queue: boost_usr_prod
  exe: /leonardo/home/userexternal/ntilinin/access-om2/bin/mppnccombine

modules:
#    use:
#        - /g/data/vk83/modules
    load:
        - access-om2

mpi:
    modulepath: /leonardo_scratch/large/userexternal/ntilinin/ACCESS-NRI/release/modules/linux-rhel8-x86_64/intel-oneapi-compilers/
    module: 2021.2.0   

# Misc
runlog: true
stacksize: unlimited
restart_freq: 1  # use tidy_restarts.py instead
mpirun: --mca io ompio --mca io_ompio_num_aggregators 1
qsub_flags: -W umask=027
env:
    UCX_LOG_LEVEL: 'error'
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 32
# sweep and resubmit on specific errors - see https://github.com/payu-org/payu/issues/241#issuecomment-610739771
userscripts:
    error: resub.sh
    run: rm -f resubmit.count

# DANGER! Do not uncomment this without checking the script is syncing to the correct location!
# postscript: sync_data.sh